import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import { properties } from "./properties/[slug]";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By Ramprasad Group
            </a>
          </div>
        </div>

        <h1>Polymer Molecular Dynamics Database</h1>

        <div className={styles.grid}>
          {Object.keys(properties).map((slug) => (
            <Link href={`/properties/${slug}`} className={styles.card}>
              <h2 className={inter.className}>
                {(properties as any)[slug]} <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Check all the simulation data for this property.
              </p>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
